#!/usr/bin/env python

import re
import sys

if len(sys.argv) != 2:
    print("Usage bootstrapify <htmlfile>")
    sys.exit(1)

page = open(sys.argv[1]).read()

# Append stylesheet
page = page.replace('</head>', '<link href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" rel="stylesheet"></head>')

# Encapsulate the content in a container
page = page.replace('<div class="center"', '<div class="container"><div class="center"')
page = page.replace('</body>', '</div></body>')

with open(sys.argv[1], "w") as outfile:
    outfile.write(page)